name 'hdp-chef'
maintainer 'Ryan Hansohn'
maintainer_email 'info@imnorobot.com'
license 'MIT'
description 'Installs/Configures hdp-chef'
version '2.4.0'
chef_version '>= 12.14'
source_url 'https://github.com/hansohn/hdp-chef'
issues_url 'https://github.com/hansohn/hdp-chef/issues'

supports 'centos', '>= 7.0'

depends 'ambari-chef'
depends 'hostsfile'
depends 'java-chef'
depends 'ulimit'
